name: dicom
channels:
  - defaults
dependencies:
  - python=3.12
  - pip:
    - dicom2nifti==2.5.1
    - fqdn==1.5.1
    - isoduration==20.11.0
    - jsonpointer==3.0.0
    - jupyterlab==4.3.5
    - matplotlib==3.10.0
    - opencv-python==4.11.0.86
    - pip==25.0
    - plotly==6.0.0
    - streamlit==1.42.2
    - tinycss2==1.4.0
    - uri-template==1.3.0
    - webcolors==24.11.1
    - wheel==0.45.1
